import type { CSSProperties } from "react";

type StyleMap = Record<string, CSSProperties>;

export const styles: StyleMap = {
  app: {
    ["--ink" as string]: "#1A1A17",
    ["--ink-soft" as string]: "#6B6A61",
    ["--bg" as string]: "#FAF9F6",
    ["--panel" as string]: "#FFFFFF",
    ["--rule-thin" as string]: "#D9D7CE",
    ["--ok" as string]: "#4A5D3A",
    ["--warn" as string]: "#C97A2B",
    ["--alert" as string]: "#B24A3B",
    background: "var(--bg)",
    minHeight: "100vh",
    padding: "24px 16px 60px",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    color: "var(--ink)",
    display: "flex",
    justifyContent: "center",
  } as CSSProperties,
  shell: { width: "100%", maxWidth: 420 },
  header: { marginBottom: 16 },
  h1: {
    fontFamily: "'Arial Narrow', Arial, sans-serif",
    fontWeight: 800,
    fontSize: 34,
    letterSpacing: "-0.01em",
    margin: 0,
    textTransform: "uppercase",
  },
  sub: { color: "var(--ink-soft)", fontSize: 14, margin: "4px 0 0" },

  tabs: { display: "flex", gap: 6, marginBottom: 16, background: "#F2F1EB", padding: 4, borderRadius: 6 },
  tab: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "8px 6px",
    fontSize: 12.5,
    fontWeight: 600,
    border: "none",
    background: "transparent",
    borderRadius: 4,
    color: "var(--ink-soft)",
    cursor: "pointer",
  },
  tabActive: { background: "var(--ink)", color: "var(--bg)" },

  dateNav: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 16 },
  dateNavBtn: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    border: "1.5px solid var(--ink)",
    background: "var(--panel)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  dateNavLabel: {
    position: "relative",
    flex: 1,
    textAlign: "center",
    fontSize: 13,
    fontWeight: 700,
    textTransform: "capitalize",
    cursor: "pointer",
  },
  dateNavInput: { position: "absolute", inset: 0, opacity: 0, cursor: "pointer", width: "100%", height: "100%" },

  dayStrip: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    background: "var(--ink)",
    color: "var(--bg)",
    padding: "10px 14px",
    borderRadius: 4,
    marginBottom: 16,
  },
  dayStripLabel: { fontSize: 12, opacity: 0.75 },
  dayStripValue: { fontFamily: "ui-monospace, monospace", fontWeight: 700, fontSize: 16, marginLeft: "auto" },
  dayStripCount: { fontSize: 12, opacity: 0.75 },

  card: { background: "var(--panel)", border: "2px solid var(--ink)", borderRadius: 6, padding: 16 },
  photoDrop: {
    height: 200,
    borderRadius: 4,
    border: "1.5px dashed var(--rule-thin)",
    backgroundColor: "#F2F1EB",
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    marginBottom: 14,
  },
  photoDropInner: { display: "flex", flexDirection: "column", alignItems: "center", gap: 8 },
  photoDropText: { fontSize: 13, color: "var(--ink-soft)", textAlign: "center", maxWidth: 200 },

  label: { fontSize: 12, color: "var(--ink-soft)", display: "block", marginBottom: 6 },
  textarea: {
    width: "100%",
    border: "1.5px solid var(--rule-thin)",
    borderRadius: 4,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    resize: "vertical",
    marginBottom: 14,
    background: "#FCFBF8",
  },
  input: {
    width: "100%",
    border: "1.5px solid var(--rule-thin)",
    borderRadius: 4,
    padding: "9px 10px",
    fontSize: 14,
    fontFamily: "inherit",
    background: "#FCFBF8",
  },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 10 },

  primaryBtn: {
    width: "100%",
    background: "var(--ink)",
    color: "var(--bg)",
    border: "none",
    borderRadius: 4,
    padding: "12px 16px",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: "0.02em",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    cursor: "pointer",
  },
  secondaryBtn: {
    flex: 1,
    background: "transparent",
    color: "var(--ink)",
    border: "1.5px solid var(--ink)",
    borderRadius: 4,
    padding: "12px 16px",
    fontSize: 14,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    cursor: "pointer",
  },
  hint: { fontSize: 11.5, color: "var(--ink-soft)", marginTop: 12, lineHeight: 1.5 },
  errorBox: {
    fontSize: 12,
    color: "var(--alert)",
    background: "#FBEAE7",
    border: "1px solid var(--alert)",
    borderRadius: 4,
    padding: "8px 10px",
    marginTop: 12,
    lineHeight: 1.4,
  },

  thumbRow: { display: "flex", gap: 12, marginBottom: 16 },
  thumb: { width: 64, height: 64, borderRadius: 4, objectFit: "cover", border: "1px solid var(--rule-thin)" },
  confidenceDot: { display: "inline-block", width: 8, height: 8, borderRadius: "50%", marginRight: 6 },
  confidenceLabel: { fontSize: 12.5, fontWeight: 700 },
  resultNote: { fontSize: 12.5, color: "var(--ink-soft)", margin: "4px 0 0", lineHeight: 1.4 },

  labelPanel: { border: "1px solid var(--ink)", borderRadius: 2, padding: "12px 14px", marginBottom: 16 },
  labelTitle: { fontFamily: "'Arial Narrow', Arial, sans-serif", fontWeight: 800, fontSize: 19, letterSpacing: "0.02em" },
  labelSub: { fontSize: 11.5, color: "var(--ink-soft)", marginBottom: 4 },
  thickRule: { height: 6, background: "var(--ink)", margin: "6px 0" },
  thinRule: { height: 1, background: "var(--rule-thin)", margin: "14px 0" },

  kcalRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", padding: "4px 0" },
  kcalLabel: { fontWeight: 700, fontSize: 15 },
  kcalValue: { fontFamily: "ui-monospace, monospace", fontWeight: 800, fontSize: 22 },
  macroRow: { display: "flex", justifyContent: "space-between", padding: "5px 0", fontSize: 13.5 },
  macroValue: { fontFamily: "ui-monospace, monospace", fontWeight: 600 },
  itemRow: { display: "flex", justifyContent: "space-between", padding: "5px 0", fontSize: 12.5 },
  itemName: { color: "var(--ink-soft)" },
  itemSource: { fontStyle: "italic" },
  itemKcal: { fontFamily: "ui-monospace, monospace" },

  portionRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    padding: "10px 12px",
    background: "#F2F1EB",
    borderRadius: 4,
  },
  portionLabel: { fontSize: 13 },
  portionControls: { display: "flex", alignItems: "center", gap: 10 },
  stepBtn: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "1.5px solid var(--ink)",
    background: "var(--panel)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  portionValue: { fontFamily: "ui-monospace, monospace", fontWeight: 700, minWidth: 40, textAlign: "center" },
  actionRow: { display: "flex", gap: 10 },

  historySection: { marginTop: 20 },
  historyHeader: {
    fontFamily: "ui-monospace, monospace",
    fontSize: 11,
    letterSpacing: "0.1em",
    color: "var(--ink-soft)",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  historyRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 0", borderBottom: "1px solid var(--rule-thin)" },
  historyThumb: { width: 36, height: 36, borderRadius: 4, objectFit: "cover" },
  historyMeta: { flex: 1, minWidth: 0 },
  historyNote: { fontSize: 12.5, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  historyTime: { fontSize: 11, color: "var(--ink-soft)" },
  historyKcal: { fontFamily: "ui-monospace, monospace", fontWeight: 700, fontSize: 13 },
  iconBtn: { border: "none", background: "transparent", color: "var(--ink-soft)", cursor: "pointer", padding: 4 },

  warnBox: {
    fontSize: 12,
    color: "var(--warn)",
    background: "#FBF1E6",
    border: "1px solid var(--warn)",
    borderRadius: 4,
    padding: "8px 10px",
    marginBottom: 14,
    lineHeight: 1.4,
  },
  bmrBox: { fontSize: 13, background: "#F2F1EB", borderRadius: 4, padding: "10px 12px", marginTop: 12 },

  balanceGrid: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, margin: "10px 0" },
  balanceLabel: { fontSize: 11, color: "var(--ink-soft)", marginBottom: 2 },
  balanceValue: { fontFamily: "ui-monospace, monospace", fontWeight: 800, fontSize: 20 },
  burnBreakdown: { marginTop: 4 },
  burnRow: { display: "flex", justifyContent: "space-between", fontSize: 12.5, padding: "4px 0", color: "var(--ink-soft)" },
  mono: { fontFamily: "ui-monospace, monospace", color: "var(--ink)" },

  emptyText: { fontSize: 12.5, color: "var(--ink-soft)" },

  groupRow: { marginBottom: 10 },
  groupLabelRow: { display: "flex", justifyContent: "space-between", fontSize: 12.5, marginBottom: 4 },
  groupDot: { display: "flex", alignItems: "center", gap: 6 },
  groupBarTrack: { height: 8, borderRadius: 4, background: "#F2F1EB", overflow: "hidden" },

  modeToggle: { display: "flex", gap: 6, background: "#F2F1EB", padding: 4, borderRadius: 6, marginBottom: 14 },
  modeToggleBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "8px 6px",
    fontSize: 12.5,
    fontWeight: 600,
    border: "none",
    background: "transparent",
    borderRadius: 4,
    color: "var(--ink-soft)",
    cursor: "pointer",
  },
  modeToggleBtnActive: { background: "var(--ink)", color: "var(--bg)" },

  noPhotoThumb: {
    width: 64,
    height: 64,
    borderRadius: 4,
    border: "1px solid var(--rule-thin)",
    background: "#F2F1EB",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--ink-soft)",
    flexShrink: 0,
  },
  noPhotoThumbSmall: {
    width: 36,
    height: 36,
    borderRadius: 4,
    background: "#F2F1EB",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--ink-soft)",
    flexShrink: 0,
  },

  libraryStrip: { display: "flex", gap: 10, overflowX: "auto", paddingBottom: 4, marginTop: 8 },
  libraryChip: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    width: 76,
    flexShrink: 0,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
  },
  libraryChipThumb: {
    width: 60,
    height: 60,
    borderRadius: "50%",
    objectFit: "cover",
    border: "1.5px solid var(--ink)",
  },
  libraryChipLabel: {
    fontSize: 10.5,
    textAlign: "center",
    lineHeight: 1.25,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    width: "100%",
  },
  libraryChipKcal: { fontSize: 10, color: "var(--ink-soft)", fontFamily: "ui-monospace, monospace" },

  editMealCard: { background: "#FCFBF8", border: "1.5px solid var(--rule-thin)", borderRadius: 4, padding: 12, margin: "8px 0" },
  editItemBlock: { border: "1px solid var(--rule-thin)", borderRadius: 4, padding: 8, marginBottom: 8, background: "var(--panel)" },
  editItemHeader: { display: "flex", gap: 6, alignItems: "center", marginBottom: 6 },
  editItemGrid: { display: "grid", gridTemplateColumns: "1.4fr 1fr 1fr 1fr 1fr", gap: 6 },
  editItemNum: { padding: "6px 4px", fontSize: 12, textAlign: "center" },
  editMealTotal: { fontSize: 12.5, color: "var(--ink-soft)", margin: "4px 0 10px" },

  editItemQuantityRow: { display: "flex", alignItems: "center", gap: 8, marginTop: 6, marginBottom: 2 },
  editItemQuantityLabel: { fontSize: 11.5, color: "var(--ink-soft)", flex: 1 },
  quantityStepBtn: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    border: "1.5px solid var(--ink)",
    background: "var(--panel)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },

  historyInfoRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 },
  historyInfoDate: { fontSize: 12.5, fontWeight: 700, textTransform: "capitalize" },
  historyInfoValue: { fontFamily: "ui-monospace, monospace", fontWeight: 800, fontSize: 15 },
  historyLegend: { display: "flex", flexWrap: "wrap", gap: 12, marginTop: 6 },
  historyLegendItem: { display: "flex", alignItems: "center", gap: 5, fontSize: 10.5, color: "var(--ink-soft)" },
  historyLegendDot: { display: "inline-block", width: 7, height: 7, borderRadius: "50%" },

  macroBenchRow: { marginBottom: 12 },
  macroBenchHeader: { display: "flex", justifyContent: "space-between", fontSize: 12.5, marginBottom: 4 },
  macroBenchStatus: { fontWeight: 700 },
  macroBenchTrack: { position: "relative", height: 10, borderRadius: 5, background: "#F2F1EB", overflow: "hidden" },
  macroBenchTarget: { position: "absolute", top: 0, bottom: 0, background: "rgba(26,26,23,0.14)" },
  macroBenchFill: { position: "absolute", top: 0, bottom: 0, left: 0, borderRadius: 5 },
  macroBenchCaption: { fontSize: 10.5, color: "var(--ink-soft)", marginTop: 3 },
};
